### ISSUE TITLE
dump to file

### ISSUE THREAD

**Issue by ghost** [frankh/nano-vanity#3]
Hey there

Could you have this dump the information to a file?

That would be great, then can leave running and come back!

**Comment by frankh** [comment]
For now you can just use shell redirects, e.g. `nano-vanity -p nano -n 0 > output.txt`

**Comment by frankh** [comment]
Actually, I don't think that will work properly because of the progress indicator... I'll have to add an option for it

**Comment by frankh** [comment]
Shell redirects should now work with quiet mode: `nano-vanity -p nano -q -n 0 > output.txt` or
`docker run --rm frankh/nano-vanity -p nano -q -n 0 > output.txt`

**Comment by xboston** [comment]
mb close this issues?
